### ISSUE TITLE
File not found error installing from pip

### ISSUE THREAD

**Issue by cccaballero** [web2py/yatl#2]
Using python 3.5 `pip install  yatl` throws:

```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yf3qncm4/yatl/setup.py", line 6, in <module>
        with open("README.md", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by mdipierro** [comment]
this was fixed in 1.0.1
