### ISSUE TITLE
Perhaps revert to {Name: yatl, Version: 20211217.1}

### ISSUE THREAD

**Issue by JoeCodeswell** [web2py/yatl#37]
Hi Massimo,

Perhaps you should revert back to {Name: yatl, Version: 20211217.1} from {Name: yatl, Version: 20220904.1} \.

**Reason**
1. After testing {Name: yatl, Version: 20220904.1} from the command line as documented in our Google Group Conversation [YATL helpers - Server-side DOM -- AttributeError: 'XML' object has no attribute 'name'](https://groups.google.com/g/py4web/c/LlgGeNOhYOQ), 
- I went back to development using 20220904.1.
    - I encountered the **Error Listing** below when using [jpsteil - grid_tutorial - Basic Example.](https://github.com/jpsteil/grid_tutorial/blob/master/docs/basic_example.md#basic-example)

2. After I reverted to {Name: yatl, Version: 20211217.1},
    - The error WENT AWAY

**Error Listing**
```python
Traceback (most recent call last):
  File "/home/USERXXXX/.local/lib/python3.8/site-packages/py4web/core.py", line 934, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/home/USERXXXX/.local/lib/python3.8/site-packages/py4web/core.py", line 919, in wrapper
    raise context["exception"]
  File "/home/USERXXXX/.local/lib/python3.8/site-packages/py4web/core.py", line 915, in wrapper
    call(fixture.on_success, context)
  File "/home/USERXXXX/.local/lib/python3.8/site-packages/py4web/core.py", line 881, in call
    return f(context)
  File "/home/USERXXXX/.local/lib/python3.8/site-packages/py4web/core.py", line 577, in on_success
    context["output"] = render(
  File "/home/USERXXXX/.local/lib/python3.8/site-packages/py4web/core.py", line 548, in render
    return engine.render(filename, context=context)
  File "/home/USERXXXX/.local/lib/python3.8/site-packages/renoir/apis.py", line 215, in render
    return self._render(source, file_path, context)
  File "/home/USERXXXX/.local/lib/python3.8/site-packages/renoir/apis.py", line 205, in _render
    make_traceback(exc_info)
  File "/home/USERXXXX/.local/lib/python3.8/site-packages/renoir/debug.py", line 116, in make_traceback
    reraise(exc_type, exc_value, tb)
  File "/home/USERXXXX/.local/lib/python3.8/site-packages/renoir/_internal.py", line 15, in reraise
    raise value.with_traceback(tb)
  File "/home/USERXXXX/btl/py4webapps/ordersarrive/templates/grid_nolayo.html", line 8, in template
    [[=grid.render()]]
  File "/home/USERXXXX/.local/lib/python3.8/site-packages/py4web/utils/grid.py", line 1377, in render
    return self._make_table()
  File "/home/USERXXXX/.local/lib/python3.8/site-packages/py4web/utils/grid.py", line 1317, in _make_table
    table.append(self._make_table_body())
  File "/home/USERXXXX/.local/lib/python3.8/site-packages/py4web/utils/grid.py", line 1093, in _make_table_body
    TD(column.render(row, index), _class=classes, _style=style)
  File "/home/USERXXXX/.local/lib/python3.8/site-packages/py4web/utils/grid.py", line 286, in render
    return self.represent(row)
  File "/home/USERXXXX/.local/lib/python3.8/site-packages/py4web/utils/grid.py", line 1102, in make_action_buttons
    cat = CAT()
  File "/home/USERXXXX/.local/lib/python3.8/site-packages/yatl/helpers.py", line 381, in __init__
    self.name = "cat"
AttributeError: can't set attribute

```

Thanks, Massimo.
Love and peace,
Joe

**Comment by mdipierro** [comment]
there was a fix for this already. can you try upgrade yatl?

**Comment by JoeCodeswell** [comment]
Hi Massimo,

As i said, the error occurred while i was using yatl, Version: 20220904.1.
I believe that is **the fix**, is it not?

The error **went away** after i reverted to the previous yatl version.

Love and peace,
Joe

**Comment by mdipierro** [comment]
This is the latest version which includes the fix
https://pypi.org/project/yatl/ 20220907.1
Did you try a  "python3 -m pip install -U yatml"?

**Comment by JoeCodeswell** [comment]
Thanks, Massimo.
With 20220907.1 my Grid is now working fine.
Thanks for the fix.
Love and peace,
Joe
