### ISSUE TITLE
name 'unicode' is not defined

### ISSUE THREAD

**Issue by davidmanns** [web2py/yatl#38]
running py4web under Python 3.10 got this error when rendering some output assembled with 
CAT(string, TABLE(...)) received this error:

Traceback (most recent call last):
  File "C:\Users/David/SkyDrive/py4web\py4web\core.py", line 163, in safely
    return func()
  File "C:\Users/David/SkyDrive/py4web\py4web\core.py", line 503, in <lambda>
    lambda: data.xml(), default=lambda: self._to_html(self._to_unicode(data))
  File "c:\Users\David\SkyDrive\py4web\venv\lib\site-packages\yatl\helpers.py", line 397, in xml
    return "".join(
  File "c:\Users\David\SkyDrive\py4web\venv\lib\site-packages\yatl\helpers.py", line 398, in <genexpr>
    s.xml() if isinstance(s, TAGGER) else xmlescape(unicode(s))
NameError: name 'unicode' is not defined

I don't think unicode() exists in Python 3, as used in helpers.py line 398?

**Comment by mdipierro** [comment]
This is now fixed in yatl 20230304.1. Thanks for reporting the problem. I
will upgrade py4web shortly to require this newer version of yatl.
